version: '3.8'

networks:
  monitoring:
    ipam:
      driver: default
      config: 
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    
volumes:
  prometheus_data: {}

services:
  # node-exporter:
  #   image: prom/node-exporter:latest
  #   container_name: node-exporter
  #   restart: unless-stopped
  #   volumes:
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
  #     - /:/rootfs:ro
  #   command:
  #     - '--path.procfs=/host/proc'
  #     - '--path.rootfs=/rootfs'
  #     - '--path.sysfs=/host/sys'
  #     - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  #   ports:
  #     - 9100:9100
  #   networks:
  #     monitoring:
  #       ipv4_address: 172.20.0.4

  traffic_generator:
    build: load
    container_name: traffic_generator
    restart: unless-stopped
    environment:
      WEBSITE_IP: '172.20.0.5'
    networks:
      monitoring:
        ipv4_address: 172.20.0.4

  website:
    build: website
    container_name: exporter
    restart: unless-stopped
    ports: 
      - 8000:8000
    networks:
      monitoring:
        ipv4_address: 172.20.0.5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      monitoring:
        ipv4_address: 172.20.0.6

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      monitoring:
        ipv4_address: 172.20.0.7
