global:
  scrape_interval: 15s

# scrape_configs:
# - job_name: app
#   static_configs:
#   - targets: ['172.20.0.4:9100']

scrape_configs:
  - job_name: website
    static_configs:
    - targets: ['172.20.0.5:8000']