{
 "title": "4 golden signals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Exporter status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_total{endpoint!=\"/metrics\"}[1m])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors/Minute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(http_request_total{endpoint!=\"metrics\", status=~\"4.+|5.+\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n    0.99,\r\n    sum(rate(http_request_duration_seconds_bucket{endpoint!=\"/metrics\"}[1m])) by (le, endpoint)\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_total{endpoint!=\"metrics\", status=~\"4.+|5.+\"}[1m])) / sum(increase(http_request_total{endpoint!=\"metrics\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_inflight_current / sum(http_request_inflight_max{job=\"website-prod\"}) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}